/* DhanRadar — generated by scripts/gen-tokens.mjs — DO NOT EDIT */
/* Source of truth: frontend/styles/tokens.json                        */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        // Static brand colours — exact values, no CSS vars
        navy:    '#0B1F3A',
        royal:   '#1E5EFF',
        emerald: { DEFAULT: '#00B386', dark: '#1FD79A' },
        cyan:    '#00C2FF',
        amber:   '#F5A623',
        red:     { DEFAULT: '#E5484D', dark: '#FF6166' },

        // Soft / tinted fills — CSS-var-backed for theme switching
        'emerald-soft':    'var(--emerald-soft)',
        'royal-blue-soft': 'var(--royal-blue-soft)',
        'red-soft':        'var(--red-soft)',
        'amber-soft':      'var(--amber-soft)',

        // Semantic surface/ink/line keys — CSS-var-backed for theme switching
        // Must match the var names emitted in tokens.css above
        bg:              'var(--bg)',
        'bg-elev':       'var(--bg-elev)',
        surface:         'var(--surface)',
        'surface-2':     'var(--surface-2)',
        'surface-3':     'var(--surface-3)',
        ink:             'var(--text)',
        'ink-secondary': 'var(--text-secondary)',
        'ink-muted':     'var(--text-muted)',
        'ink-faint':     'var(--text-faint)',
        line:            'var(--border)',
        'line-strong':   'var(--border-strong)',
      },
      fontFamily: {
        sans:  ['var(--font-geist-sans)', 'Geist', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono:  ['var(--font-geist-mono)', 'Geist Mono', 'ui-monospace', 'SF Mono', 'monospace'],
        serif: ['var(--font-instrument-serif)', 'Instrument Serif', 'Georgia', 'serif'],
      },
      fontSize: {
        display: ['64px', { lineHeight: '1.02', letterSpacing: '-0.035em', fontWeight: '500' }],
        h1:      ['40px',      { lineHeight: '1.05',      letterSpacing: '-0.025em',      fontWeight: '500' }],
        h2:      ['28px',      { lineHeight: '1.15',      letterSpacing: '-0.02em',      fontWeight: '500' }],
        h3:      ['18px',      { lineHeight: '1.3',      letterSpacing: '-0.01em',      fontWeight: '500' }],
        body:    ['15px',    { lineHeight: '1.55',    letterSpacing: '-0.005em' }],
        small:   ['13px',   { lineHeight: '1.45' }],
        caption: ['11px', { lineHeight: '1.3', letterSpacing: '0.08em', fontWeight: '500' }],
      },
      spacing: {
        '5': '20px',
      },
      borderRadius: {
        sm:   '4px',
        md:   '8px',
        lg:   '12px',
        xl:   '14px',
        '2xl':'18px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(15,20,35,0.04)',
        md: '0 4px 16px rgba(15,20,35,0.06)',
        lg: '0 24px 60px -20px rgba(15,20,35,0.18)',
      },
      transitionDuration: {
        fast: '120ms',
        base: '240ms',
        slow: '400ms',
      },
      transitionTimingFunction: {
        out:    'cubic-bezier(0.16,1,0.3,1)',
        'in-out': 'cubic-bezier(0.4,0,0.2,1)',
      },
      zIndex: {
        dropdown: '10',
        sticky:   '20',
        overlay:  '30',
        modal:    '40',
        toast:    '50',
      },
    },
  },
};
