/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a free-tier account (password; sets cookies). OTP-first rejected (D2). */
        post: operations["authSignup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate (generic 401 on any failure; no enumeration) */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear cookies, revoke refresh + access jti */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Silent refresh — reads __Host-refresh cookie, rotates (reuse detection). No body. */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate TOTP secret + provisioning URI */
        post: operations["authTotpSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify TOTP code and activate 2FA */
        post: operations["authTotpVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscription plans (from plans catalog, D4) */
        get: operations["billingPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Razorpay order */
        post: operations["billingCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Razorpay webhook (CURRENT live path). Verify-before-parse on raw bytes (X-Razorpay-Signature) + 7-day event-id dedup. Server-to-server. */
        post: operations["subscriptionsWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Razorpay webhook (TARGET path). Step 7 re-mounts the live handler here (verify-before-parse + event dedup preserved); /subscriptions/webhook kept as an alias for one release. SPEC until Step 7 lands. */
        post: operations["billingWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autosuggest (Postgres FTS + pg_trgm; NOT Elasticsearch, non-neg */
        get: operations["instrumentsSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock detail (label+band public; numerics gated) */
        get: operations["getStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{isin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fund detail */
        get: operations["getFund"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etfs/{isin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ETF detail */
        get: operations["getEtf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public score — returns ScorePublic (label + confidence band) ONLY. Numeric internals are NEVER on this ungated surface (no-numeric-in-DOM, non-neg #2); they are served exclusively by the tier-gated /score/detail. */
        get: operations["getScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/score/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tier-gated numeric score view (Score): unified_score + per-axis values + fair_value. Factor WEIGHTS are never exposed even here. Requires auth; 402 for free/anonymous. */
        get: operations["getScoreDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/fair-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multi-model fair value (Pro; numeric — gated) */
        get: operations["getFairValue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain/{entity_type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Why this ranking drawer (deterministic factor decomposition; no weights) */
        get: operations["explainRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scored picks (educational). `label` filter — advisory `signal` enum REJECTED. */
        get: operations["listRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio overview */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings */
        get: operations["getHoldings"];
        put?: never;
        /** Add holding */
        post: operations["addHolding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk/attribution (Pro) */
        get: operations["getPortfolioAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists */
        get: operations["getWatchlists"];
        put?: never;
        /** Create list */
        post: operations["createWatchlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alert rules + events */
        get: operations["getAlerts"];
        put?: never;
        /** Create alert rule */
        post: operations["createAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grounded AI answer (quota-gated) */
        post: operations["aiSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assistant (SSE stream of AIAnswer deltas) */
        post: operations["aiAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/explain/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explainability for a score */
        get: operations["aiExplain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News feed */
        get: operations["getNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/mood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mood Compass (09:00 & 16:00 IST) */
        get: operations["getMood"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/why-today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Why the market moved today */
        get: operations["getWhyToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/track-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public track record (ISR) */
        get: operations["getTrackRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consent status */
        get: operations["getConsentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-rights/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** File a DPDP data-rights request (access/correction/erasure/portability) */
        post: operations["dataRightsRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Canonical error type slugs: validation_error(400) · unauthorized(401) · invalid_credentials(401) · upgrade_required(402) · consent_required(403) · forbidden(403) · not_found(404) · conflict(409) · unprocessable(422) · rate_limited(429) · invalid_signature(400) · internal(500) · upstream_unavailable(502/503). */
        Problem: {
            /**
             * Format: uri
             * @example https://dhanradar.com/errors/upgrade_required
             */
            type: string;
            /** @example Upgrade required */
            title: string;
            /** @example 402 */
            status: number;
            /**
             * @description Instance message; no stack-trace/PII.
             * @example This feature requires the Pro tier.
             */
            detail?: string;
            /** @example /api/v1/instruments/INFY/fair-value */
            instance?: string;
            /** Format: uuid */
            request_id: string;
        };
        /**
         * @description Non-advisory educational label (architecture §S2.2). No buy/sell verbs.
         * @enum {string}
         */
        Label: "in_form" | "on_track" | "off_track" | "out_of_form" | "insufficient_data";
        /**
         * @description Confidence band only (numeric % suppressed until calibration gate).
         * @enum {string}
         */
        ConfidenceBand: "high" | "medium" | "low";
        /** @enum {string} */
        InstrumentType: "stock" | "fund" | "etf";
        /** @enum {string} */
        Tier: "anonymous" | "free" | "pro" | "pro_plus" | "founder_lifetime";
        /**
         * @description Five-axis DhanRadar Score (FINAL_SCORING_SPEC). Trend holds Growth sub-factors.
         * @enum {string}
         */
        FactorAxis: "quality" | "valuation" | "momentum" | "risk" | "trend";
        /** @enum {string} */
        AlertType: "price" | "score" | "risk" | "earnings";
        /** @enum {string} */
        AlertOperator: "gt" | "lt" | "eq" | "crosses";
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TOTPVerifyRequest: {
            code: string;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            tier: components["schemas"]["Tier"];
            totp_verified: boolean;
            /** @enum {string|null} */
            risk_profile?: "conservative" | "moderate" | "aggressive" | null;
            dpdp_consent_version?: string | null;
        };
        MessageUser: {
            message: string;
            user: components["schemas"]["UserResponse"];
        };
        MessageResponse: {
            message: string;
        };
        TOTPSetupResponse: {
            provisioning_uri: string;
            secret: string;
        };
        HealthResponse: {
            /** @example ok */
            status?: string;
            /** @example ok */
            db?: string;
            /** @example ok */
            redis?: string;
        };
        Instrument: {
            /** Format: uuid */
            id?: string;
            symbol?: string;
            exchange?: string;
            type?: components["schemas"]["InstrumentType"];
            name?: string;
            sector?: string;
            price?: number | null;
            change_pct?: number | null;
            label?: components["schemas"]["Label"];
            confidence_band?: components["schemas"]["ConfidenceBand"];
        };
        /** @description Ungated score view. NO numeric score / factors / fair_value. */
        ScorePublic: {
            label: components["schemas"]["Label"];
            confidence_band: components["schemas"]["ConfidenceBand"];
            /** Format: date-time */
            valid_until?: string | null;
            model_version: string;
            /** Format: date */
            as_of: string;
            contributing_signals?: string[];
            contradicting_signals?: string[];
            /** @description In-force disclaimer version this label was served under (ai_recommendation_audit tie-in, non-neg #9). */
            disclaimer_version?: string | null;
        };
        /** @description Gated score view (numeric internals). Served only to authorized tiers; factor WEIGHTS are never exposed even here. */
        Score: components["schemas"]["ScorePublic"] & {
            score?: number;
            factors?: {
                quality?: number;
                valuation?: number;
                momentum?: number;
                risk?: number;
                trend?: number;
            };
            fair_value?: number | null;
            /** @description Numeric % — null until calibration gate opens. */
            confidence?: number | null;
        };
        Plan: {
            id?: string;
            name?: string;
            price_inr?: number;
            /** @enum {string} */
            interval?: "month" | "year" | "lifetime";
            features?: string[];
        };
        CheckoutRequest: {
            plan_id: string;
        };
        CheckoutResponse: {
            order_id?: string;
            amount_inr?: number;
            /** @description Razorpay publishable key id (NOT a secret); safe for client use. */
            razorpay_key_id?: string;
        };
        Holding: {
            instrument?: components["schemas"]["Instrument"];
            qty?: number;
            avg_price?: number;
            value?: number;
            pnl_pct?: number;
        };
        AlertRule: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            instrument_id?: string;
            type?: components["schemas"]["AlertType"];
            operator?: components["schemas"]["AlertOperator"];
            threshold?: number;
            active?: boolean;
        };
        AlertCreateRequest: {
            /** Format: uuid */
            instrument_id: string;
            type: components["schemas"]["AlertType"];
            operator: components["schemas"]["AlertOperator"];
            threshold: number;
        };
        AISearchRequest: {
            query: string;
        };
        /** @description Every AI output carries reasoning, confidence band, sources, NOT_ADVICE. */
        AIAnswer: {
            answer?: string;
            reasoning?: string;
            confidence_band?: components["schemas"]["ConfidenceBand"];
            sources?: {
                name?: string;
                freshness?: string;
            }[];
            model_version?: string;
            /** @example NOT_ADVICE: educational information only. */
            disclaimer?: string;
        };
    };
    responses: {
        /** @description Bad request */
        Problem400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not authenticated */
        Problem401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Upgrade required */
        Problem402: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Forbidden / consent required */
        Problem403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found */
        Problem404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflict */
        Problem409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limited */
        Problem429: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Required on all mutating + payment endpoints; server dedupes by key. */
        IdempotencyKey: string;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Degraded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    authSignup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Account created (Set-Cookie __Host-access/__Host-refresh) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageUser"];
                };
            };
            409: components["responses"]["Problem409"];
            429: components["responses"]["Problem429"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in (Set-Cookie) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageUser"];
                };
            };
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens rotated (Set-Cookie) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Problem401"];
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["UserResponse"];
                    };
                };
            };
            401: components["responses"]["Problem401"];
        };
    };
    authTotpSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPSetupResponse"];
                };
            };
            401: components["responses"]["Problem401"];
        };
    };
    authTotpVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPVerifyRequest"];
            };
        };
        responses: {
            /** @description Verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Problem401"];
        };
    };
    billingPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"][];
                };
            };
        };
    };
    billingCheckout: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on all mutating + payment endpoints; server dedupes by key. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Order created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            402: components["responses"]["Problem402"];
        };
    };
    subscriptionsWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged (also for deduped replays) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
        };
    };
    billingWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged (also for deduped replays) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
        };
    };
    instrumentsSearch: {
        parameters: {
            query: {
                q: string;
                scope?: "all" | "stocks" | "funds" | "etfs";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"][];
                };
            };
        };
    };
    getStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
            404: components["responses"]["Problem404"];
        };
    };
    getFund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
            404: components["responses"]["Problem404"];
        };
    };
    getEtf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
            404: components["responses"]["Problem404"];
        };
    };
    getScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorePublic"];
                };
            };
            404: components["responses"]["Problem404"];
        };
    };
    getScoreDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Score"];
                };
            };
            402: components["responses"]["Problem402"];
            404: components["responses"]["Problem404"];
        };
    };
    getFairValue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            402: components["responses"]["Problem402"];
        };
    };
    explainRanking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRecommendations: {
        parameters: {
            query?: {
                label?: components["schemas"]["Label"];
                sector?: string;
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorePublic"][];
                };
            };
            402: components["responses"]["Problem402"];
        };
    };
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHoldings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"][];
                };
            };
        };
    };
    addHolding: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on all mutating + payment endpoints; server dedupes by key. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPortfolioAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            402: components["responses"]["Problem402"];
        };
    };
    getWatchlists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createWatchlist: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on all mutating + payment endpoints; server dedupes by key. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAlert: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on all mutating + payment endpoints; server dedupes by key. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    aiSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AISearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAnswer"];
                };
            };
            429: components["responses"]["Problem429"];
        };
    };
    aiAssistant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    aiExplain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAnswer"];
                };
            };
        };
    };
    getNews: {
        parameters: {
            query?: {
                ticker?: string;
                sector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMood: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWhyToday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTrackRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getConsentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dataRightsRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on all mutating + payment endpoints; server dedupes by key. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
