#!/usr/bin/env node
/**
 * gen-tokens.mjs — DhanRadar token pipeline
 *
 * Reads: frontend/styles/tokens.json  (single source of truth)
 * Emits:
 *   frontend/src/styles/tokens.css       — :root (light) + .theme-dark (dark)
 *   frontend/tailwind.tokens.cjs         — theme.extend for tailwind preset
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const root  = join(__dir, '..');

// `--check` (CI) regenerates in memory and fails if the committed files are stale,
// instead of writing — so the generated tokens can never silently drift from
// tokens.json (the design-system single source of truth).
const CHECK = process.argv.includes('--check');
let stale = false;

function emit(relPath, content) {
  const abs = join(root, relPath);
  if (CHECK) {
    const current = existsSync(abs) ? readFileSync(abs, 'utf8') : '';
    if (current !== content) {
      stale = true;
      console.error(`✗  STALE: ${relPath} — run \`npm run gen:tokens\``);
    } else {
      console.log(`✓  fresh: ${relPath}`);
    }
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content, 'utf8');
    console.log(`✓  ${relPath}`);
  }
}

const tokens = JSON.parse(readFileSync(join(root, 'styles', 'tokens.json'), 'utf8'));

const c      = tokens.color;
const typ    = tokens.type;
const sp     = tokens.spacing;
const rad    = tokens.radius;
const shd    = tokens.shadow;
const motion = tokens.motion;
const zIdx   = tokens.zIndex;

// Turn a CSS font-family list string ("var(--x), 'Geist', sans-serif") into a
// Tailwind fontFamily array literal — so the Tailwind preset and tokens.css are
// both generated from the SAME tokens.json source (no hand-maintained drift).
const famArr = (s) =>
  '[' +
  s
    .split(',')
    .map((t) => t.trim().replace(/^'(.*)'$/, '$1'))
    .map((t) => `'${t}'`)
    .join(', ') +
  ']';

// "#RRGGBB" (or "#RGB") → "R G B" channel triplet. The semantic theme colours
// additionally emit `--<name>-rgb` channel vars so Tailwind's alpha modifier
// (e.g. `bg-surface/95`) works on CSS-var-backed colours — a plain
// `var(--surface)` colour silently generates NO utility for `/N` classes
// (RCA 2026-08-17: every sticky bar using `bg-surface/95` was transparent).
const hexToChannels = (hex) => {
  const h = hex.replace('#', '');
  const full = h.length === 3 ? [...h].map((ch) => ch + ch).join('') : h;
  if (!/^[0-9a-fA-F]{6}$/.test(full)) {
    throw new Error(`hexToChannels: not a hex colour: ${hex}`);
  }
  return [0, 2, 4].map((i) => parseInt(full.slice(i, i + 2), 16)).join(' ');
};

// The alpha-capable semantic set — hex in BOTH themes (dark border/borderStrong
// are rgba() strings, so line/line-strong stay plain vars, no `/N` support).
// [cssVarName, tokens.json key]
const RGB_KEYS = [
  ['bg', 'bg'],
  ['bg-elev', 'bgElev'],
  ['surface', 'surface'],
  ['surface-2', 'surface2'],
  ['surface-3', 'surface3'],
  ['text', 'text'],
  ['text-secondary', 'textSecondary'],
  ['text-muted', 'textMuted'],
  ['text-faint', 'textFaint'],
];
const rgbVarLines = (theme) =>
  RGB_KEYS.map(([v, k]) => `  --${v}-rgb: ${hexToChannels(theme[k])};`).join('\n');

// ---------------------------------------------------------------------------
// 1.  tokens.css
// ---------------------------------------------------------------------------
const css = `/* DhanRadar — generated by scripts/gen-tokens.mjs — DO NOT EDIT */
/* Source of truth: frontend/styles/tokens.json                        */

:root {
  /* --- Brand colours (static, never theme-switch) --- */
  --dr-navy:        ${c.brand.deepNavy.value};
  --dr-royal:       ${c.brand.royalBlue.value};
  --dr-emerald:     ${c.brand.emerald.value};
  --dr-emerald-dark:${c.brand.emeraldDark.value};
  --dr-cyan:        ${c.accent.cyan.value};
  --dr-amber:       ${c.accent.amber.value};
  --dr-red:         ${c.accent.red.value};
  --dr-red-dark:    ${c.accent.redDark.value};

  /* --- Typography families --- */
  --dr-font-sans:   ${typ.family.sans};
  --dr-font-mono:   ${typ.family.mono};
  --dr-font-serif:  ${typ.family.serif};

  /* --- Spacing scale --- */
  --dr-space-1:  ${sp['1']};
  --dr-space-2:  ${sp['2']};
  --dr-space-3:  ${sp['3']};
  --dr-space-4:  ${sp['4']};
  --dr-space-5:  ${sp['5']};
  --dr-space-6:  ${sp['6']};
  --dr-space-8:  ${sp['8']};
  --dr-space-12: ${sp['12']};
  --dr-space-16: ${sp['16']};

  /* --- Border radii --- */
  --dr-r-sm:   ${rad.sm};
  --dr-r-md:   ${rad.md};
  --dr-r-lg:   ${rad.lg};
  --dr-r-xl:   ${rad.xl};
  --dr-r-2xl:  ${rad['2xl']};
  --dr-r-full: ${rad.full};

  /* --- Shadows (light) --- */
  --shadow-sm: ${shd.sm};
  --shadow-md: ${shd.md};
  --shadow-lg: ${shd.lg};

  /* --- Motion --- */
  --duration-fast: ${motion.duration.fast};
  --duration-base: ${motion.duration.base};
  --duration-slow: ${motion.duration.slow};
  --ease-out:      ${motion.easing.out};
  --ease-in-out:   ${motion.easing.inOut};

  /* --- Z-index scale --- */
  --z-dropdown: ${zIdx.dropdown};
  --z-sticky:   ${zIdx.sticky};
  --z-overlay:  ${zIdx.overlay};
  --z-modal:    ${zIdx.modal};
  --z-toast:    ${zIdx.toast};

  /* --- Soft / tinted fills (light) --- */
  --emerald-soft:    ${c.soft.emeraldSoft.light};
  --royal-blue-soft: ${c.soft.royalBlueSoft.light};
  --red-soft:        ${c.soft.redSoft.light};
  --amber-soft:      ${c.soft.amberSoft.light};

  /* --- Semantic / theme vars (light defaults in :root) --- */
  --bg:             ${c.light.bg};
  --bg-elev:        ${c.light.bgElev};
  --surface:        ${c.light.surface};
  --surface-2:      ${c.light.surface2};
  --surface-3:      ${c.light.surface3};
  --border:         ${c.light.border};
  --border-strong:  ${c.light.borderStrong};
  --text:           ${c.light.text};
  --text-secondary: ${c.light.textSecondary};
  --text-muted:     ${c.light.textMuted};
  --text-faint:     ${c.light.textFaint};

  /* --- Channel triplets (alpha-capable Tailwind colours, e.g. bg-surface/95) --- */
${rgbVarLines(c.light)}
}

/* Dark theme — applied via .theme-dark class on <html> or a parent */
.theme-dark {
  --bg:             ${c.dark.bg};
  --bg-elev:        ${c.dark.bgElev};
  --surface:        ${c.dark.surface};
  --surface-2:      ${c.dark.surface2};
  --surface-3:      ${c.dark.surface3};
  --border:         ${c.dark.border};
  --border-strong:  ${c.dark.borderStrong};
  --text:           ${c.dark.text};
  --text-secondary: ${c.dark.textSecondary};
  --text-muted:     ${c.dark.textMuted};
  --text-faint:     ${c.dark.textFaint};

  /* Dark shadow overrides */
  --shadow-sm: ${shd.darkSm};
  --shadow-md: ${shd.darkMd};
  --shadow-lg: ${shd.darkLg};

  /* Soft / tinted fills (dark) */
  --emerald-soft:    ${c.soft.emeraldSoft.dark};
  --royal-blue-soft: ${c.soft.royalBlueSoft.dark};
  --red-soft:        ${c.soft.redSoft.dark};
  --amber-soft:      ${c.soft.amberSoft.dark};

  /* Channel triplets (alpha-capable Tailwind colours) */
${rgbVarLines(c.dark)}
}
`;

emit('src/styles/tokens.css', css);

// ---------------------------------------------------------------------------
// 2.  tailwind.tokens.cjs
// ---------------------------------------------------------------------------
const cjsContent = `/* DhanRadar — generated by scripts/gen-tokens.mjs — DO NOT EDIT */
/* Source of truth: frontend/styles/tokens.json                        */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        // Static brand colours — exact values, no CSS vars
        navy:    '${c.brand.deepNavy.value}',
        royal:   '${c.brand.royalBlue.value}',
        emerald: { DEFAULT: '${c.brand.emerald.value}', dark: '${c.brand.emeraldDark.value}' },
        cyan:    '${c.accent.cyan.value}',
        amber:   '${c.accent.amber.value}',
        red:     { DEFAULT: '${c.accent.red.value}', dark: '${c.accent.redDark.value}' },

        // Soft / tinted fills — CSS-var-backed for theme switching
        'emerald-soft':    'var(--emerald-soft)',
        'royal-blue-soft': 'var(--royal-blue-soft)',
        'red-soft':        'var(--red-soft)',
        'amber-soft':      'var(--amber-soft)',

        // Semantic surface/ink/line keys — CSS-var-backed for theme switching.
        // rgb(var(--x-rgb) / <alpha-value>) so the /N alpha modifier works
        // (plain var(--x) colours silently drop /N utilities — RCA 2026-08-17).
        // line/line-strong stay plain vars: their dark values are rgba() strings.
        bg:              'rgb(var(--bg-rgb) / <alpha-value>)',
        'bg-elev':       'rgb(var(--bg-elev-rgb) / <alpha-value>)',
        surface:         'rgb(var(--surface-rgb) / <alpha-value>)',
        'surface-2':     'rgb(var(--surface-2-rgb) / <alpha-value>)',
        'surface-3':     'rgb(var(--surface-3-rgb) / <alpha-value>)',
        ink:             'rgb(var(--text-rgb) / <alpha-value>)',
        'ink-secondary': 'rgb(var(--text-secondary-rgb) / <alpha-value>)',
        'ink-muted':     'rgb(var(--text-muted-rgb) / <alpha-value>)',
        'ink-faint':     'rgb(var(--text-faint-rgb) / <alpha-value>)',
        line:            'var(--border)',
        'line-strong':   'var(--border-strong)',
      },
      fontFamily: {
        sans:  ${famArr(typ.family.sans)},
        mono:  ${famArr(typ.family.mono)},
        serif: ${famArr(typ.family.serif)},
      },
      fontSize: {
        display: ['${typ.scale.display.size}', { lineHeight: '${typ.scale.display.lineHeight}', letterSpacing: '${typ.scale.display.letterSpacing}', fontWeight: '${typ.scale.display.weight}' }],
        h1:      ['${typ.scale.h1.size}',      { lineHeight: '${typ.scale.h1.lineHeight}',      letterSpacing: '${typ.scale.h1.letterSpacing}',      fontWeight: '${typ.scale.h1.weight}' }],
        h2:      ['${typ.scale.h2.size}',      { lineHeight: '${typ.scale.h2.lineHeight}',      letterSpacing: '${typ.scale.h2.letterSpacing}',      fontWeight: '${typ.scale.h2.weight}' }],
        h3:      ['${typ.scale.h3.size}',      { lineHeight: '${typ.scale.h3.lineHeight}',      letterSpacing: '${typ.scale.h3.letterSpacing}',      fontWeight: '${typ.scale.h3.weight}' }],
        body:    ['${typ.scale.body.size}',    { lineHeight: '${typ.scale.body.lineHeight}',    letterSpacing: '${typ.scale.body.letterSpacing}' }],
        small:   ['${typ.scale.small.size}',   { lineHeight: '${typ.scale.small.lineHeight}' }],
        caption: ['${typ.scale.caption.size}', { lineHeight: '${typ.scale.caption.lineHeight}', letterSpacing: '${typ.scale.caption.letterSpacing}', fontWeight: '${typ.scale.caption.weight}' }],
        micro:   ['${typ.scale.micro.size}',   { lineHeight: '${typ.scale.micro.lineHeight}',   letterSpacing: '${typ.scale.micro.letterSpacing}',   fontWeight: '${typ.scale.micro.weight}' }],
      },
      spacing: {
        '5': '${sp['5']}',
      },
      borderRadius: {
        sm:   '${rad.sm}',
        md:   '${rad.md}',
        lg:   '${rad.lg}',
        xl:   '${rad.xl}',
        '2xl':'${rad['2xl']}',
      },
      boxShadow: {
        sm: '${shd.sm}',
        md: '${shd.md}',
        lg: '${shd.lg}',
      },
      transitionDuration: {
        fast: '${motion.duration.fast}',
        base: '${motion.duration.base}',
        slow: '${motion.duration.slow}',
      },
      transitionTimingFunction: {
        out:    '${motion.easing.out}',
        'in-out': '${motion.easing.inOut}',
      },
      zIndex: {
        dropdown: '${zIdx.dropdown}',
        sticky:   '${zIdx.sticky}',
        overlay:  '${zIdx.overlay}',
        modal:    '${zIdx.modal}',
        toast:    '${zIdx.toast}',
      },
    },
  },
};
`;

emit('tailwind.tokens.cjs', cjsContent);

if (CHECK) {
  if (stale) {
    console.error('\nDesign tokens are stale. Run `npm run gen:tokens` and commit the result.');
    process.exit(1);
  }
  console.log('\nDesign tokens are in sync with tokens.json.');
} else {
  console.log('\nToken generation complete.');
}
