#!/usr/bin/env node
/**
 * gen-tokens.mjs — DhanRadar token pipeline
 *
 * Reads: frontend/styles/tokens.json  (single source of truth)
 * Emits:
 *   frontend/src/styles/tokens.css       — :root (light) + .theme-dark (dark)
 *   frontend/tailwind.tokens.cjs         — theme.extend for tailwind preset
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const root  = join(__dir, '..');

const tokens = JSON.parse(readFileSync(join(root, 'styles', 'tokens.json'), 'utf8'));

const c   = tokens.color;
const typ = tokens.type;
const sp  = tokens.spacing;
const rad = tokens.radius;
const shd = tokens.shadow;

// ---------------------------------------------------------------------------
// 1.  tokens.css
// ---------------------------------------------------------------------------
const css = `/* DhanRadar — generated by scripts/gen-tokens.mjs — DO NOT EDIT */
/* Source of truth: frontend/styles/tokens.json                        */

:root {
  /* --- Brand colours (static, never theme-switch) --- */
  --dr-navy:        ${c.brand.deepNavy.value};
  --dr-royal:       ${c.brand.royalBlue.value};
  --dr-emerald:     ${c.brand.emerald.value};
  --dr-emerald-dark:${c.brand.emeraldDark.value};
  --dr-cyan:        ${c.accent.cyan.value};
  --dr-amber:       ${c.accent.amber.value};
  --dr-red:         ${c.accent.red.value};
  --dr-red-dark:    ${c.accent.redDark.value};

  /* --- Typography families --- */
  --dr-font-sans:   ${typ.family.sans};
  --dr-font-mono:   ${typ.family.mono};
  --dr-font-serif:  ${typ.family.serif};

  /* --- Spacing scale --- */
  --dr-space-1:  ${sp['1']};
  --dr-space-2:  ${sp['2']};
  --dr-space-3:  ${sp['3']};
  --dr-space-4:  ${sp['4']};
  --dr-space-6:  ${sp['6']};
  --dr-space-8:  ${sp['8']};
  --dr-space-12: ${sp['12']};
  --dr-space-16: ${sp['16']};

  /* --- Border radii --- */
  --dr-r-sm:   ${rad.sm};
  --dr-r-md:   ${rad.md};
  --dr-r-lg:   ${rad.lg};
  --dr-r-xl:   ${rad.xl};
  --dr-r-2xl:  ${rad['2xl']};
  --dr-r-full: ${rad.full};

  /* --- Shadows (light) --- */
  --shadow-sm: ${shd.sm};
  --shadow-md: ${shd.md};
  --shadow-lg: ${shd.lg};

  /* --- Semantic / theme vars (light defaults in :root) --- */
  --bg:             ${c.light.bg};
  --bg-elev:        ${c.light.bgElev};
  --surface:        ${c.light.surface};
  --surface-2:      ${c.light.surface2};
  --surface-3:      ${c.light.surface3};
  --border:         ${c.light.border};
  --border-strong:  ${c.light.borderStrong};
  --text:           ${c.light.text};
  --text-secondary: ${c.light.textSecondary};
  --text-muted:     ${c.light.textMuted};
  --text-faint:     ${c.light.textFaint};
}

/* Dark theme — applied via .theme-dark class on <html> or a parent */
.theme-dark {
  --bg:             ${c.dark.bg};
  --bg-elev:        ${c.dark.bgElev};
  --surface:        ${c.dark.surface};
  --surface-2:      ${c.dark.surface2};
  --surface-3:      ${c.dark.surface3};
  --border:         ${c.dark.border};
  --border-strong:  ${c.dark.borderStrong};
  --text:           ${c.dark.text};
  --text-secondary: ${c.dark.textSecondary};
  --text-muted:     ${c.dark.textMuted};
  --text-faint:     ${c.dark.textFaint};

  /* Dark shadow overrides */
  --shadow-sm: ${shd.darkSm};
  --shadow-md: ${shd.darkMd};
  --shadow-lg: ${shd.darkLg};
}
`;

mkdirSync(join(root, 'src', 'styles'), { recursive: true });
writeFileSync(join(root, 'src', 'styles', 'tokens.css'), css, 'utf8');
console.log('✓  src/styles/tokens.css');

// ---------------------------------------------------------------------------
// 2.  tailwind.tokens.cjs
// ---------------------------------------------------------------------------
const cjsContent = `/* DhanRadar — generated by scripts/gen-tokens.mjs — DO NOT EDIT */
/* Source of truth: frontend/styles/tokens.json                        */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        // Static brand colours — exact values, no CSS vars
        navy:    '${c.brand.deepNavy.value}',
        royal:   '${c.brand.royalBlue.value}',
        emerald: { DEFAULT: '${c.brand.emerald.value}', dark: '${c.brand.emeraldDark.value}' },
        cyan:    '${c.accent.cyan.value}',
        amber:   '${c.accent.amber.value}',
        red:     { DEFAULT: '${c.accent.red.value}', dark: '${c.accent.redDark.value}' },

        // Semantic surface/ink/line keys — CSS-var-backed for theme switching
        // Must match the var names emitted in tokens.css above
        bg:              'var(--bg)',
        surface:         'var(--surface)',
        'surface-2':     'var(--surface-2)',
        'surface-3':     'var(--surface-3)',
        ink:             'var(--text)',
        'ink-secondary': 'var(--text-secondary)',
        'ink-muted':     'var(--text-muted)',
        'ink-faint':     'var(--text-faint)',
        line:            'var(--border)',
        'line-strong':   'var(--border-strong)',
      },
      fontFamily: {
        sans:  ['Geist', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono:  ['Geist Mono', 'ui-monospace', 'SF Mono', 'monospace'],
        serif: ['Instrument Serif', 'Georgia', 'serif'],
      },
      fontSize: {
        display: ['${typ.scale.display.size}', { lineHeight: '${typ.scale.display.lineHeight}', letterSpacing: '${typ.scale.display.letterSpacing}', fontWeight: '${typ.scale.display.weight}' }],
        h1:      ['${typ.scale.h1.size}',      { lineHeight: '${typ.scale.h1.lineHeight}',      letterSpacing: '${typ.scale.h1.letterSpacing}',      fontWeight: '${typ.scale.h1.weight}' }],
        h2:      ['${typ.scale.h2.size}',      { lineHeight: '${typ.scale.h2.lineHeight}',      letterSpacing: '${typ.scale.h2.letterSpacing}',      fontWeight: '${typ.scale.h2.weight}' }],
        h3:      ['${typ.scale.h3.size}',      { lineHeight: '${typ.scale.h3.lineHeight}',      letterSpacing: '${typ.scale.h3.letterSpacing}',      fontWeight: '${typ.scale.h3.weight}' }],
        body:    ['${typ.scale.body.size}',    { lineHeight: '${typ.scale.body.lineHeight}',    letterSpacing: '${typ.scale.body.letterSpacing}' }],
        small:   ['${typ.scale.small.size}',   { lineHeight: '${typ.scale.small.lineHeight}' }],
        caption: ['${typ.scale.caption.size}', { lineHeight: '${typ.scale.caption.lineHeight}', letterSpacing: '${typ.scale.caption.letterSpacing}', fontWeight: '${typ.scale.caption.weight}' }],
      },
      borderRadius: {
        sm:   '${rad.sm}',
        md:   '${rad.md}',
        lg:   '${rad.lg}',
        xl:   '${rad.xl}',
        '2xl':'${rad['2xl']}',
      },
      boxShadow: {
        sm: '${shd.sm}',
        md: '${shd.md}',
        lg: '${shd.lg}',
      },
    },
  },
};
`;

writeFileSync(join(root, 'tailwind.tokens.cjs'), cjsContent, 'utf8');
console.log('✓  tailwind.tokens.cjs');

console.log('\nToken generation complete.');
