/* DhanRadar — generated by scripts/gen-concepts.mjs — DO NOT EDIT */
/* Source of truth: src/data/concepts.json + src/data/components.json                */
import conceptsData from './concepts.json';
import componentsData from './components.json';
import type { ComponentDef, ConceptDef } from './registry.types';

/** Every concept id in the registry (literal union, for type-safe consumers). */
export type ConceptId =
  | 'portfolio.summary'
  | 'holdings.list'
  | 'holding.transactions'
  | 'holdings.xirr'
  | 'holdings.pnl'
  | 'portfolio.valuation_series'
  | 'portfolio.allocation'
  | 'portfolio.allocation_sector'
  | 'portfolio.overlap'
  | 'portfolio.concentration'
  | 'portfolio.health'
  | 'portfolio.diversification'
  | 'portfolio.risk'
  | 'portfolio.risk_advanced'
  | 'portfolio.cost'
  | 'portfolio.performance'
  | 'portfolio.benchmark'
  | 'portfolio.projection'
  | 'portfolio.tax'
  | 'goals.list'
  | 'goals.progress'
  | 'fund.label'
  | 'fund.head'
  | 'fund.nav_series'
  | 'fund.analytics'
  | 'fund.rank_history'
  | 'fund.composition'
  | 'fund.people'
  | 'fund.amc'
  | 'fund.peers'
  | 'fund.factors'
  | 'fund.signals'
  | 'fund.sip_illustration'
  | 'fund.health'
  | 'fund.changes'
  | 'portfolio.score_raw'
  | 'mood.current'
  | 'portfolio.recommendations'
  | 'portfolio.opportunities'
  | 'portfolio.ai_feed'
  | 'portfolio.ai_summary'
  | 'portfolio.timeline'
  | 'portfolio.reports'
  | 'advice.suitability'
  | 'sync.status';

export const CONCEPTS = conceptsData.concepts as readonly ConceptDef[];
export const COMPONENTS = componentsData.components as readonly ComponentDef[];

/** O(1) lookup of a concept's registry row by id. */
export const conceptMeta: Readonly<Record<ConceptId, ConceptDef>> = Object.freeze(
  Object.fromEntries(CONCEPTS.map((c) => [c.concept, c])) as Record<ConceptId, ConceptDef>,
);

/**
 * Single TanStack query-key factory for any concept (§5). One shape, never duplicated —
 * coexists with the hand-maintained keys in lib/queryKeys.ts.
 *   conceptKey('holdings.list', portfolioId)
 */
export const conceptKey = (concept: ConceptId, ...scope: (string | number)[]) =>
  ['concept', concept, ...scope] as const;
